package firtree.utilities;

/**
 * Extends {@link mltk.core.Instance} to be used in the coordinate ascent algorithm
 * 
 * @author Xiaojie Wang
 */
public class Instance extends mltk.core.Instance {

	// Cache the previous prediction for an instance to speed up training
	protected double prediction;
	// Instances with the same group id are collectively called a query group
	protected String groupId;
	// Index in the list of all nodes in a FirTree model, but must be a leaf node's index
	protected int nodeIndex = -1;
	
	public Instance(mltk.core.Instance instance) {
		super(instance);
	}
	
	public boolean isIndexed() {
		if (nodeIndex == -1)
			return false;
		return true;
	}

	// The following getters and setters are automatically generated by Eclipse
	public double getPrediction() {
		return prediction;
	}

	public void setPrediction(double prediction) {
		this.prediction = prediction;
	}

	public int getNodeIndex() {
		return nodeIndex;
	}

	public void setNodeIndex(int nodeIndex) {
		this.nodeIndex = nodeIndex;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}
	
}
