package firtree.utilities;

import mltk.core.io.AttrInfo;

/**
 * Extends {@link mltk.core.Instance} to be used in the coordinate ascent algorithm
 * 
 * @author Xiaojie Wang
 */
public class Instance extends mltk.core.Instance {

	AttrInfo ainfoLeaf;
	// Cache the previous prediction for an instance to speed up training
	protected double prediction;
	// Index in the list of all nodes in a FirTree model, but must be a leaf node's index
	protected int nodeIndex = -1;
	
	// Used for evaluation
	public Instance(double target) {
		super(target);
	}
	
	public Instance(mltk.core.Instance instance, AttrInfo ainfoLeaf) {
		super(instance);
		this.ainfoLeaf = ainfoLeaf;
	}
	
	public int getAttId(String attName) {
		return ainfoLeaf.nameToId.get(attName);
	}
	
	public boolean isIndexed() {
		if (nodeIndex == -1)
			return false;
		return true;
	}

	// The following getters and setters are automatically generated by Eclipse
	public double getPrediction() {
		return prediction;
	}

	public void setPrediction(double prediction) {
		this.prediction = prediction;
	}

	public int getNodeIndex() {
		return nodeIndex;
	}

	public void setNodeIndex(int nodeIndex) {
		this.nodeIndex = nodeIndex;
	}
}
